### ISSUE TITLE
InputManager.getCursorControllers().size() == 0.

### ISSUE THREAD

**Issue by codeczx** [gearvrf/GearVRf-Demos#430]
Hi,i ran the project gvr-controller but i could not get GVRCursorController.Here is the code in SimpleMain.java.

 GVRInputManager inputManager = gvrContext.getInputManager();
 inputManager.addCursorControllerListener(cursorControllerListener);
Log.i("test","controller size:"+inputManager.getCursorControllers().size());
for (GVRCursorController cursor : inputManager.getCursorControllers()) {
       cursorControllerListener.onCursorControllerAdded(cursor);
}

I got the log "controller size : 0". I can connect the controller to the SamSumg S7 .When i pressed the back button,i could enter the page that asked me if i want to quit this app.My controller is this one:
https://www.oculus.com/blog/introducing-samsungs-new-gear-vr-with-controllerpowered-by-oculus/

I can get GVRCursorController only when i add"useGazeCursorController="true" and "useAndroidWearTouchpad="true"to the gvr.xml . I found this way in gvr-events ,but it can not solve my problem.What should i do?

**Comment by rahul27** [comment]
Hi @codeczx are you building the framework yourself? This sample requires a more recent version of the Framework(one that includes the following pull request):

https://github.com/Samsung/GearVRf/pull/1101

**Comment by codeczx** [comment]
@rahul27 No,i git clone the whole project (GearVRf-Demos) after you commit "Adding a sample to demo the controller support".I think i use the latest version of the Framework.

**Comment by thomasflynn** [comment]
The demos pull from the 3.1.2-SNAPSHOT which gets updated regularly from master, but could end up stale on your machine.  Actually, here's the relevant line from the FAQ in the Wiki:

"We push updated framework snapshots to the maven repo we use but due to the gradle's caching you are most likely using outdated snapshot. Please pass the --refresh-dependencies argument to gradlew if you are building from the command line. Or you can just delete the gradle cache via rm -rf ~/.gradle/caches/."

let us know if that helps.

**Comment by liaxim** [comment]
The snapshot on the maven repo was updated today.

**Comment by rahul27** [comment]
@codeczx can we close this issue?

**Comment by codeczx** [comment]
Yes.
