### ISSUE TITLE
Suggest include APK (and even screenshot) files in this repo?

### ISSUE THREAD

**Issue by danke-sra** [gearvrf/GearVRf-Demos#7]
It would be easier for developers to try and know what the sample is about.

**Comment by liaxim** [comment]
APK sounds like a good idea. We need an automated way of producing them.

**Comment by thomasflynn** [comment]
how do we handle oculus signature files??  anyone wanting to run an apk will need one in the assets folder of the apk.

**Comment by danke-sra** [comment]
That's a good question. Not an easy one -- they still need to add their osig into the APK before running. We can provide a script for doing that. Not sure about the demand. The idea is just to help them pick the right demo and try it out.

**Comment by thomasflynn** [comment]
and that script would need to be platform independent.  we have users on Linux, Windows, and Mac.

**Comment by danke-sra** [comment]
If needed, we can do it with python. It is cross-platform.

**Comment by danke-sra** [comment]
I have a better idea. The APK is optional. But if monoscopic mode is fixed, we can include APKs in monoscopic mode.

To ensure demos are of high-quality, we can ask contributors to provide a README.md file for each demo, and provide a template like this: https://github.com/kimkulling/osre/tree/master/samples/00_HelloWorld

**Comment by thomasflynn** [comment]
yeah, had the same thought earlier today about monoscopic.  After Mihail gets done some of the other things I've asked him, i've also asked him to look into the vrapi port which will give us back the flexibility to re-enable monoscopic on non-samsung phones.  though, it won't be quick to to do.  if it was quick to do, i would've already done it ;-)

also the READMEs are a good idea.

**Comment by jbueza** [comment]
Hi @danke-sra and @thomasflynn and @liaxim , 

I'm coming in pretty late in this discussion but I came across it because Oculus Signature files have been a huge pain for any developer building for GearVR. That said, I recently built ConstructVR (https://constructvr.io) which was built for the GearVR development community to easily share private GearVR apps and remove the headaches of passing around OSig files since the Android app automates this process. 

It is completely free for the community and built to help speed up development and testing. I've also written up [a blogpost here on how it works](https://medium.com/@jbueza/how-to-share-your-gearvr-apps-with-your-clients-customers-and-testers-733055eeef2a#.tx3ouvnl0).

If you have any feedback or questions, please let me know because I'm always looking for ways to help the community with better tools! 

Kind regards,
Jaime Bueza

**Comment by thomasflynn** [comment]
Hi Jaime.  We're getting close to a point where we can try this out.  We need to straighten out our apk names first.  (a lot of samples were created by referencing / copying a previous sample, so, several have the same name).  That's in the process of being fixed.  We have an internal automated build that happens every night just to make sure the build doesn't break.  Once we have our apks names straightened out, we could give deploying apks to constructvr a try.  ConstructVR could be a useful solution.  We'll share our experience with you when we get there.

**Comment by jbueza** [comment]
Hi @thomasflynn !

Thanks for the quick response! [ConstructVR](https://constructvr.io)'s goal is to create tools to help rapid development and testing for the GearVR development community -- I'm excited to help out anyway we can! :shipit: 🚀 

Kind regards,
Jaime Bueza

**Comment by liaxim** [comment]
It doesn't seem like the original idea (include apks) is ever going to realize. Planning to close one of these days.
